server:
  port: 80

spring:
  mail:
    host: smtp.163.com
    username: lei1882022@163.com
    password: ENC(a6L39gjaEF/6f22iiE8djm9/FHHFQ/D8zUQIEW1g2Jo=)
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Œ™ jasypt ≈‰÷√Ω‚√‹√ÿ‘ø
jasypt:
  encryptor:
    password: spring-boot-demo